
    create table Consultoras (
        id bigint generated by default as identity (start with 1),
        cantidad_empleados integer,
        nombre varchar(255),
        primary key (id)
    )

    create table Proyectos (
        id bigint generated by default as identity (start with 1),
        costo_estimado numeric(19,2),
        nombre varchar(255),
        consultora_encargada bigint,
        primary key (id)
    )

    alter table Proyectos 
        add constraint FK_9k1vuiwhv4c8jjbwasomybi7g 
        foreign key (consultora_encargada) 
        references Consultoras
